// Generated by CoffeeScript 1.6.3
/*

Hit
  if > 21, bust
  if === 21, dealer gets card
    dealer must keep getting cards until === 21 or bust

Stand
  dealer gets new card
  keep adding cards
*/


(function() {
  describe("deck constructor", function() {
    var deck;
    deck = new Deck();
    it("should access attributes", function() {
      expect(typeof deck.at(0).attributes.rank).toBe('number');
      expect(typeof deck.at(0).attributes.suitName).toBe('string');
      return expect(typeof deck.at(0).attributes.value).toBe('number');
    });
    return it("should create a card collection", function() {
      var collection;
      collection = new Deck();
      return expect(collection.length).toBe(52);
    });
  });

}).call(this);
