// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      _ref = App.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    App.prototype.initialize = function() {
      var deck,
        _this = this;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      this.get('playerHand').on('stand', function() {
        var _results;
        console.log('App -> stand');
        this.get('dealerHand').models[0].flip();
        _results = [];
        while (this.get('dealerHand').scores() < 17) {
          _results.push(this.get('dealerHand').hit());
        }
        return _results;
      }, this);
      this.get('dealerHand').on('bust', function() {
        return console.log('app --> dealerHand bust');
      });
      return this.get('playerHand').on('bust', function() {
        return alert('you are busted');
      });
    };

    return App;

  })(Backbone.Model);

}).call(this);
